export const products = [
  {
    slug: "encode-campus",
    name: "Encode Campus",
    tagline: "Education Operating & Governance Platform",
    short: "Operate Education",
    theme: "black",
    description:
      "Encode Campus is Encode Studio's education technology platform designed to help institutions manage operations, people, data, governance and institutional workflows through a unified digital ecosystem.",
    positioning: "One platform. One institutional data foundation. One operating layer for education.",
    capabilities: [
      "Institution Management",
      "Academic Operations",
      "Student Management",
      "Staff & Faculty Management",
      "Organisation & User Management",
      "Roles & Permissions",
      "Module Entitlements",
      "Institutional Data Management",
      "Governance",
      "Dashboards & Alerts",
      "Data Quality & Provenance",
      "Operational Workflows",
      "Reporting & Analytics",
    ],
    scaleStory: ["Schools", "Colleges", "Universities", "Coaching Institutes"],
  },
  {
    slug: "encode-learn",
    name: "Encode Learn",
    tagline: "Learning & Knowledge Platform",
    short: "Enable Learning",
    theme: "blue",
    description:
      "A modern digital learning environment designed to make knowledge accessible, structured and engaging — positioned as a dedicated learning product rather than simply another LMS.",
    positioning: "Learning, Reimagined.",
    capabilities: [
      "Course Management",
      "Learning Paths",
      "Content Delivery",
      "Assessments",
      "Progress Tracking",
      "Learner Profiles",
      "Instructor Tools",
      "Knowledge Resources",
      "Analytics",
      "Digital Credentials",
    ],
  },
  {
    slug: "encode-verify",
    name: "Encode Verify",
    tagline: "Verification & Trust Platform",
    short: "Establish Trust",
    theme: "black-blue",
    description:
      "A verification and validation platform designed to help organisations establish confidence in information, credentials, documents and claims.",
    positioning: "Trust Every Record.",
    capabilities: [
      "Document Verification",
      "Credential Verification",
      "Identity / Record Validation",
      "Verification Requests",
      "Verification Status",
      "Digital Records",
      "Audit Trails",
      "Verification APIs",
      "Trust Signals",
    ],
  },
];

export const serviceGroups = [
  {
    id: "strategy",
    number: "01",
    name: "Product Strategy & Consulting",
    tagline: "Help clients figure out what to build before they build it.",
    services: [
      "Product Discovery",
      "Digital Strategy",
      "Business & Product Consulting",
      "Requirements Analysis",
      "Product Roadmapping",
      "Technology Consulting",
      "MVP Planning",
      "Digital Transformation Consulting",
      "Technical Feasibility Assessment",
    ],
  },
  {
    id: "design",
    number: "02",
    name: "UI/UX & Product Design",
    tagline: "Design experiences people actually want to use.",
    services: [
      "UX Research",
      "Information Architecture",
      "User Journey Design",
      "Wireframing",
      "UI Design",
      "Design Systems",
      "Product Prototyping",
      "Responsive Web Design",
      "Mobile App Design",
      "Usability Improvements",
      "UX Audits",
    ],
  },
  {
    id: "web",
    number: "03",
    name: "Web Development",
    tagline: "Fast. Scalable. Production-ready.",
    services: [
      "Corporate Websites",
      "Marketing Websites",
      "SaaS Platforms",
      "Web Applications",
      "Customer Portals",
      "Admin Dashboards",
      "Enterprise Web Applications",
      "API-driven Applications",
      "Progressive Web Applications",
    ],
  },
  {
    id: "mobile",
    number: "04",
    name: "Mobile App Development",
    tagline: "Build mobile experiences across platforms.",
    services: [
      "Android Applications",
      "iOS Applications",
      "Cross-platform Applications",
      "Consumer Apps",
      "Business Applications",
      "Education Applications",
      "Mobile UI/UX",
      "App Maintenance & Enhancement",
    ],
  },
  {
    id: "engineering",
    number: "05",
    name: "Software & Product Engineering",
    tagline: "One of Encode Studio's strongest service categories.",
    services: [
      "Custom Software Development",
      "SaaS Product Development",
      "MVP Development",
      "Enterprise Applications",
      "Backend Engineering",
      "API Development",
      "Database Architecture",
      "Third-party Integrations",
      "Multi-tenant Architecture",
      "Scalable System Architecture",
      "Legacy System Modernisation",
    ],
  },
  {
    id: "ai",
    number: "06",
    name: "AI, Automation & Intelligent Systems",
    tagline: "Turn software into intelligent systems.",
    services: [
      "AI Product Development",
      "AI-powered Applications",
      "Generative AI Solutions",
      "AI Assistants",
      "Intelligent Search",
      "Document Intelligence",
      "Workflow Automation",
      "AI Integrations",
      "Data-driven Automation",
      "AI Proof-of-Concepts",
      "AI-enabled Business Workflows",
    ],
  },
  {
    id: "cloud",
    number: "07",
    name: "Cloud, DevOps & Infrastructure",
    tagline: "Build for scale from day one.",
    services: [
      "Cloud Architecture",
      "Cloud Deployment",
      "Application Infrastructure",
      "CI/CD",
      "DevOps",
      "Database Infrastructure",
      "Monitoring",
      "Performance Optimisation",
      "Security Hardening",
      "Scalability Engineering",
      "Backup & Disaster Recovery",
    ],
  },
  {
    id: "growth",
    number: "08",
    name: "Product Maintenance & Growth",
    tagline: "We build products for the long run.",
    services: [
      "Product Maintenance",
      "Technical Support",
      "Performance Optimisation",
      "Feature Development",
      "Product Evolution",
      "Security Updates",
      "Infrastructure Management",
      "Analytics & Optimisation",
      "Continuous Improvement",
      "Long-term Technology Partnership",
    ],
  },
];

export const process = [
  { number: "01", name: "Discover", desc: "Understand the business, users and problem." },
  { number: "02", name: "Define", desc: "Convert the problem into a clear product strategy." },
  { number: "03", name: "Design", desc: "Create intuitive experiences and scalable design systems." },
  { number: "04", name: "Build", desc: "Engineer the product using modern technology." },
  { number: "05", name: "Launch", desc: "Deploy, test and take the product into production." },
  { number: "06", name: "Evolve", desc: "Measure, improve and continuously develop." },
];

export const differentiators = [
  { name: "Product Thinking", desc: "We don't just write code. We understand the product behind the software." },
  { name: "Engineering Depth", desc: "We design systems that can evolve beyond the MVP." },
  { name: "Design + Technology", desc: "Strategy, UX and engineering work together." },
  { name: "Built for Scale", desc: "Architecture is designed around future growth." },
  { name: "AI-Native Thinking", desc: "We identify opportunities where AI and automation can genuinely improve products." },
  { name: "Long-Term Partnership", desc: "We can remain involved after launch." },
];

export const interestOptions = [
  "Building a new product",
  "Website / Web Application",
  "Mobile App",
  "AI / Automation",
  "Digital Transformation",
  "Encode Campus",
  "Encode Learn",
  "Encode Verify",
  "Other",
];
